require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'spec/rubocop/fixtures/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
